### PR TITLE
rewrite changeAction event to broadcast to main stream

### PR DESCRIPTION
**Pull request by cmyui**

### CODE REVIEW

**Review by tsunyoku — CHANGES_REQUESTED** [review]
what happened to `serverPackets.userPanel`...?

**Comment by cmyui** [comment]
> what happened to `serverPackets.userPanel`...?

I noticed it's not sent in bancho.py:

https://github.com/osuAkatsuki/bancho.py/blob/0c03c03c67fde7378d804ead11a333904a0431e6/app/api/domains/cho.py#L298

Do u know if there was a specific reason we were sending it here? I can test these changes locally to ensure no regression

**Comment by tsunyoku** [comment]
i don't, bancho.py seems correct. just wasn't sure if the removal was intended

**Review by tsunyoku — APPROVED** [review]

**Comment by cmyui** [comment]
Tested locally and seems good

**Pull request merged**
