### PR TITLE
Rewrite redis ops in session data enqueue() and dequeue() to fix race condition

### PR DESCRIPTION
**Pull request by infernalfire72**

### CODE REVIEW

**Review by tsunyoku — DISMISSED** [review]
i hate it but it's fine

**Comment by infernalfire72** [comment]
Le

**Review by tsunyoku — DISMISSED** [review]
LE

**Comment by cmyui** [comment]
lE

**Comment by cmyui** [comment]
> we need to upgrade redis first - not supported on current ver

My apologies for the lack of detail in my message -- was speaking to LPOP support for the `count` argument:

image

**Comment by cmyui** [comment]
Hrm... After upgrading to 6.2.0 locally I'm seeing redis intermittently drop connections `redis.exceptions.ConnectionError: Connection closed by server.`

I think we'll need to figure that out before I'm comfortable upgrading in production

**Comment by cmyui** [comment]
For now I'm going to change this to use a redis pipeline to fix the atomicity bug

image

**Review by cmyui — APPROVED** [review]

**Review by cmyui — APPROVED** [review]

**Pull request merged**
