### PR TITLE
fix: nowranked embed

### PR DESCRIPTION
**Pull request by mistralwz**
just replaced emote id since i deleted and broke it...

### CODE REVIEW

**Comment by mistralwz** [comment]
@cmyui why is the nerinyan mirror removed btw? they're still up - and so is osudirect... beatconnect is the least likely to work rn since they barely support unranked maps

**Comment by mistralwz** [comment]
ok, i've looked at blame and i assume we would like to use our own mirror more...? i can change the embed a bit more around that...

**Comment by mistralwz** [comment]
image
here's the slightly updated concept: the song title now leads to akatsuki beatmap listing (where they can download the map using our mirror, and the 3 other "mirrors", including bancho (often slow).

**Comment by cmyui** [comment]
Using beatmaps.akatsuki.gg will automatically load balance, retry and weight based on latency and failure rate between mino, osu.direct, nerinyan and any other mirrors; none of our software other than beatmaps service needs to know about any of the specific mirrors anymore, they should all just go thru beatmaps service

**Comment by cmyui** [comment]
I left beatconnect as it's the one mirror that beatmaps service isn't yet integrated with -- we should try to get an api key and integrate it

**Review by cmyui — APPROVED** [review]

**Pull request merged**
